version: '3'
services:
  postgres:
    image: postgres:14.5-bullseye
    container_name: my_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres-kawamoto
      - POSTGRES_PASSWORD=postgreshkhkhk
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

  flask:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_container
    tty: true
    volumes:
      - ./:/usr/src/app
    ports:
      - "5000:5000"
